config/routes.rb
Rails.application.routes.draw do

  devise_for :live_houses, controllers: {
    sessions: "devise/live_houses/sessions",
    registrations: "devise/live_houses/registrations"
  }

  devise_for :users, skip: [:registrations, :sessions ]

  devise_scope :user do
    get 'signin' => 'devise/users/sessions#new', as: :new_user_session
    post 'signin' => 'devise/users/sessions#create', as: :user_session
    delete 'sign_out' => 'devise/users/sessions#destroy', as: :destroy_user_session
    get 'signup' => 'devise/users/registrations#new', as: :new_user_registration
    post 'signup' => 'devise/users/registrations#create', as: :user_registration
    post 'guest_sign_in' => 'devise/users/sessions#guest_sign_in', as: :user_guest_sign
  end

  devise_for :admins, controllers: {
    sessions: "devise/admins/sessions",
    registrations: "devise/admins/registrations"
  }

  namespace :live_house do
    get 'calendar' => 'lives#calendar'
    resources :mypages, only:[:new, :show, :edit]
    resources :schedules, only:[:index]
    resources :lives, only:[:new, :create, :show]
    resources :user, only:[:show]
  end

  scope module: :public do
    root to: 'homes#top'
    get 'home_lives' => 'homes#lives'
    resources :live_houses, only: [:index, :show]
    resources :favorites, only: [:create, :destroy]
    resources :live_organizations, only: [:create]
    resources :lives, only: [:new, :create, :show]
    get 'calendar' => 'lives#calendar'
    resources :notifications, only: :index
    resources :relationships, only: [:create, :destroy]
    resources :bands, only:[:index, :edit, :update]
    resources :articles, only:[:show, :create, :destroy] do
      resource :favorites, only: [:create, :destroy]
      resources :comments, only: [:create, :destroy]
    end

    get 'users/:id/edit' => 'users#edit' ,as: 'edit_mypage'
    get 'users/:id' => 'users#show', as: 'mypage'
    patch 'users/mypage/update' => 'users#update'
    resources :bands do
      member do
        get :following, :followers
      end
    end
  end

  namespace :admin do
    root to: 'homes#top'
    resources :user_bands, only:[:index, :show, :update]
    resources :users, only:[:index, :show]
    resources :live_houses, only:[:edit, :show, :index, :update]
    resources :lives, only:[:index, :edit, :update]
  end

  if Rails.env.development?
    mount LetterOpenerWeb::Engine, at: '/letter_opener'
  end
end

app/controllers/admin/live_houses_controller.rb
class Admin::LiveHousesController < ApplicationController
  before_action :set_live_house, only: [:show, :edit, :update]
  before_action :authenticate_admin!
  skip_before_action :authenticate_user!

  def index
    @live_houses = LiveHouse.all
  end

  def show
  end

  def edit
  end

  def update
    @live_house.update(live_house_params)
    redirect_to admin_live_houses_path
  end

  private

  def live_house_params
    params.require(:live_house).permit(:price, :house_name, :address, :telephone_number,
                                       :image, :detail, :postal_code, :website, :is_active)
  end

  def set_live_house
    @live_house = LiveHouse.find(params[:id])
  end
end

app/helpers/admin/live_houses_helper.rb
module Admin::LiveHousesHelper
end

app/views/admin/live_houses/edit.html.erb
  <%= form_with model:@live_house, url:admin_live_house_path(@live_house), local:true do |f| %>
   <div class="form-group">
   <label>Picture</label>
   <%= f.attachment_field :image%>
   </div>

   <div class="form-group">
   <label>name</label>
   <%= f.text_field :house_name, class:"form-control"  %>
   </div>

   <div class="form-group">
   <label>Postal Code</label>
   <%= f.text_area :postal_code, class:"form-control"  %>
   </div>

   <div class="form-group">
   <label>address</label>
   <%= f.text_area :address, class:"form-control"  %>
   </div>

   <div class="form-group">
   <label>TELL</label>
   <%= f.text_area :telephone_number, class:"form-control"  %>
   </div>

   <div class="form-group">
   <label>price</label>
   <%= f.text_field :price, class:"form-control" %>
   </div>

   <div class="form-group">
   <label>website</label>
   <%= f.text_field :website, class:"form-control" %>
   </div>

   <div class="form-group">
   <label>status</label></br>
   open <%= f.radio_button :is_active, :true, checked: true %>
   close <%= f.radio_button :is_active, :false %>
   </div>

   <%= f.submit 'Update', class:"btn btn-secondary btn-md" %>
  <% end %>

app/views/admin/live_houses/index.html.erb
<div class="container">

	<h1>Live Houses</h1>

	<div class="row">
		<table class="table table-dark table-sm">
			<thead class="thead-dark">
				<tr>
					<th>ID</th>
					<th>Name</th>
					<th>Price</th>
					<th>Scadule</th>
					<th>Status</th>
					<th>Edit</th>
					<th>Delete</th>
				</tr>
			</thead>
			<tbody>
				<% @live_houses.each do |live_house| %>
					<tr>
						<td><%= live_house.id %></td>
						<td><%= link_to live_house.house_name, admin_live_house_path(live_house) %></td>
						<td><%= converting_to_jpy(live_house.price) %></td>
						<td>scadule</td>
						<td><%= live_house.is_active %></td>
						<td><%= link_to "Edit", edit_admin_live_house_path(live_house), class:"btn btn-success btn-sm" %></td>
						<td><%= link_to "Delete",admin_live_house_path(live_house), method: :delete, class:"btn btn-danger btn-sm" %></td>
				</tr>
				<% end %>
			</tbody>
		</table>
	</div>
</div>

app/views/admin/live_houses/show.html.erb
<div class="container">
  <div class="row">
    <div class="col-sm-4">
      <h1><%= @live_house.house_name %></h1>
      <table>
        <tbody>
          <tr>
            <td>Website</td>
            <td><%= link_to @live_house.website.truncate(30),@live_house.website %></td>
          </tr>
          <tr>
            <td>Price</td>
            <td><%= @live_house.price%></td>
          </tr>
          <tr>
            <td>Postal Code</td>
            <td><%= @live_house.postal_code%></td>
          </tr>
          <tr>
            <td>Address</td>
            <td><%= @live_house.address%></td>
          </tr>
          <tr>
            <td>TELL</td>
            <td><%= @live_house.telephone_number%></td>
          </tr>
          <tr>
            <td>Detail</td>
            <td><%= @live_house.detail%></td>
          </tr>
        </tbody>
      </table>
    </div>
    <div class="col-sm-4">
      <%= attachment_image_tag @live_house, :image, size: "300x300", fallback: "no_image.png", size: "300x300"%>
    </div>
    <div id='map' class="col-sm-4">

    </div>
  </div>

  <script src="https://maps.googleapis.com/maps/api/js?key=AIzaSyBYghblosto1WOuW2btc0E9GpvmpNtGM7E&callback=initMap" async defer></script>
  <script>
    let map
    function initMap(){
      const geocoder = new google.maps.Geocoder()

      const map = new google.maps.Map(document.getElementById('map'), {
        //latが緯度、lngが経度を示します
        center: {
          lat: <%= @live_house.latitude %>,
          lng: <%= @live_house.longitude %>
        },
        //数値は0〜21まで指定できます。数値が大きいほど拡大されます
        zoom: 12,
      });
      //positionに指定した座標にピンを表示させます
      const marker = new google.maps.Marker({
        position:  {
          lat: <%= @live_house.latitude %>,
          lng: <%= @live_house.longitude %>
        },
        map: map
      });
    }
  </script>

</div>