config/routes.rb
Rails.application.routes.draw do

  devise_for :live_houses, controllers: {
    sessions: "devise/live_houses/sessions",
    registrations: "devise/live_houses/registrations"
  }

  devise_for :users, skip: [:registrations, :sessions ]

  devise_scope :user do
    get 'signin' => 'devise/users/sessions#new', as: :new_user_session
    post 'signin' => 'devise/users/sessions#create', as: :user_session
    delete 'sign_out' => 'devise/users/sessions#destroy', as: :destroy_user_session
    get 'signup' => 'devise/users/registrations#new', as: :new_user_registration
    post 'signup' => 'devise/users/registrations#create', as: :user_registration
    post 'guest_sign_in' => 'devise/users/sessions#guest_sign_in', as: :user_guest_sign
  end

  devise_for :admins, controllers: {
    sessions: "devise/admins/sessions",
    registrations: "devise/admins/registrations"
  }

  namespace :live_house do
    get 'calendar' => 'lives#calendar'
    resources :mypages, only:[:new, :show, :edit]
    resources :schedules, only:[:index]
    resources :lives, only:[:new, :create, :show]
    resources :user, only:[:show]
  end

  scope module: :public do
    root to: 'homes#top'
    get 'home_lives' => 'homes#lives'
    resources :live_houses, only: [:index, :show]
    resources :favorites, only: [:create, :destroy]
    resources :live_organizations, only: [:create]
    resources :lives, only: [:new, :create, :show]
    get 'calendar' => 'lives#calendar'
    resources :notifications, only: :index
    resources :relationships, only: [:create, :destroy]
    resources :bands, only:[:index, :edit, :update]
    resources :articles, only:[:show, :create, :destroy] do
      resource :favorites, only: [:create, :destroy]
      resources :comments, only: [:create, :destroy]
    end

    get 'users/:id/edit' => 'users#edit' ,as: 'edit_mypage'
    get 'users/:id' => 'users#show', as: 'mypage'
    patch 'users/mypage/update' => 'users#update'
    resources :bands do
      member do
        get :following, :followers
      end
    end
  end

  namespace :admin do
    root to: 'homes#top'
    resources :user_bands, only:[:index, :show, :update]
    resources :users, only:[:index, :show]
    resources :live_houses, only:[:edit, :show, :index, :update]
    resources :lives, only:[:index, :edit, :update]
  end

  if Rails.env.development?
    mount LetterOpenerWeb::Engine, at: '/letter_opener'
  end
end

app/models/live_house.rb
class LiveHouse < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :lives, class_name: 'Live'
  attachment :image

  # 郵便番号
  validates :postal_code, presence: true, format:
                                        {
                                          with: /\A\d{7}\z/,
                                          message: "ハイフンなし7桁で入力してください",
                                        }
  # 電話番号
  validates :telephone_number, presence: true, format:
                                            {
                                              with: /\A\d{10}$|^\d{11}\z/,
                                              message: "ハイフンなし10桁または11桁で入力してください",
                                            }

  geocoded_by :address
  after_validation :geocode
end

app/controllers/admin/lives_controller.rb
class Admin::LivesController < ApplicationController
  skip_before_action :authenticate_user!
  before_action :authenticate_admin!

  def index
    @lives = Live.where(registered_person: true)
  end

  def update
    @live = Live.find(params[:id])
    if @live.update(status: "waiting_live")
      redirect_to admin_lives_path
    else
      @lives = Live.all
      render :index
    end
  end

  private

  def live_params
    params.require(:live).permit(:status)
  end
end

app/controllers/live_house/lives_controller.rb
class LiveHouse::LivesController < ApplicationController
  skip_before_action :authenticate_user!
  before_action :authenticate_live_house!

  def new
    @live_houses = LiveHouse.all
    @live_house = current_live_house
    @lives = Live.where(live_house_id: @live_house.id)
    @live = Live.new
    respond_to do |format|
      # リクエストされるフォーマットがHTML形式の場合
      format.html
      # リクエストされるフォーマットがJSON形式の場合
      format.json { render :new }
      # @livesをjson形式のデータへ変換して返す
    end
  end

  def create
    @live_houses = LiveHouse.all
    @lives = Live.where(live_house_id: current_live_house.id)
    @live_insert = false
    @lives.each do |compare_live|
      if params[:live][:start_at].between?(compare_live.start_at, compare_live.end_at) ||
        params[:live][:end_at].between?(compare_live.start_at, compare_live.end_at)
        @live_insert = true
      end
    end

    if @live_insert
      flash.now[:danger] = "予定の作成に失敗しました"
      @live = Live.new
      render :new
    else
      live = Live.new(live_params)
      live.registered_person = false
      live.live_house_id = current_live_house.id
      live.status = "live_house"
      live.color = "gray"
      if live.save
        redirect_to live_house_schedules_path
      else
        flash.now[:danger] = "予定の作成に失敗しました"
        @live = Live.new
        render :new
      end
    end
  end

  def show
    @live = LiveHouse.find(params[:id])
  end

  private

  def live_params
    params.require(:live).permit(:start_at, :end_at, :live_name, :introduction)
  end
end

app/controllers/live_house/mypages_controller.rb
class LiveHouse::MypagesController < ApplicationController
  skip_before_action :authenticate_user!
  before_action :authenticate_live_house!

  def show
    @live_house = LiveHouse.find(params[:id])
    @live = Live.new
    @lives = Live.where(live_house_id: params[:id])

    respond_to do |format|
      # リクエストされるフォーマットがHTML形式の場合
      format.html

      # リクエストされるフォーマットがJSON形式の場合
      format.json { render :show }
      # @livesをjson形式のデータへ変換して返す
    end
  end

  def edit
  end
end

app/controllers/live_house/scadules_controller.rb
class LiveHouse::ScadulesController < ApplicationController
  skip_before_action :authenticate_user!
  before_action :authenticate_live_house!

  def index
    @lives = Live.all
    @band_lives = Live.where(registered_person: true)
    respond_to do |format|
      # リクエストされるフォーマットがHTML形式の場合
      format.html

      # リクエストされるフォーマットがJSON形式の場合
      format.json { render :new }
      # @livesをjson形式のデータへ変換して返す
    end
  end
end

app/controllers/live_house/schedules_controller.rb
class LiveHouse::SchedulesController < ApplicationController
  skip_before_action :authenticate_user!
  before_action :authenticate_live_house!

  def index
    @lives = Live.all
    @band_lives = Live.where(registered_person: true)
    respond_to do |format|
      # リクエストされるフォーマットがHTML形式の場合
      format.html

      # リクエストされるフォーマットがJSON形式の場合
      format.json { render :new }
      # @livesをjson形式のデータへ変換して返す
    end
  end
end

app/helpers/admin/lives_helper.rb
module Admin::LivesHelper
end

app/helpers/live_house/homes_helper.rb
module LiveHouse::HomesHelper
end

app/helpers/live_house/lives_helper.rb
module LiveHouse::LivesHelper
end

app/helpers/live_house/mypage_helper.rb
module LiveHouse::MypageHelper
end

app/helpers/live_house/scadules_helper.rb
module LiveHouse::ScadulesHelper
end

app/views/live_house/lives/calendar.js.erb
$("#new2_live").modal("show");

app/views/live_house/lives/new.html.erb
<div class="container">

    <h1 class="mb-5"><%= current_live_house.house_name%></h1>
      <div class="modal fade" id="new2_live">
        <div class="modal-dialog" role="document">
          <div class="modal-content">
            <div class="modal-header">
              <h5 class="modal-title">New live</h5>
              <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                <span aria-hidden="true">&times;</span>
              </button>
            </div>
            <div class="modal-body">

              <div id="calendar" >
              </div>
            </div>
          </div>
        </div>
      </div>

    <%= form_with model: @live, url: live_house_lives_path, local: true do |f| %>
      <div class="form-group row">
        <%= f.label :live_name, "予定", class: "form-control-label col-sm-2 col-form-label"%>
        <div class="col-sm-10">
          <%= f.text_field :live_name, class:"form-control" %>
        </div>
      </div>

      <div class="form-group row">
        <%= f.label :start_at, "No Live", class: "form-control-label col-sm-2 col-form-label"%>
        <div class="col-sm-3">
          <%= f.text_field :start_at, class: "form-control input-start"%>
        </div>
        <div class="col-sm-3">
          <%= f.text_field :end_at, class: "form-control input-end"%>
        </div>
        <div class="col-sm-3">
          <%= link_to "calendar",live_house_calendar_path, remote: true, class: "btn btn-lg, btn-primary" %>
        </div>
      </div>

      <div class="form-group row">
        <%= f.label :introduction, "Note", class: "form-control-label col-sm-2 col-form-label"%>
        <div class="col-sm-10">
          <%= f.text_area :introduction, class:"form-control" %>
        </div>
      </div>

      <div class="form-group text-right">
        <%= f.submit "入力完了", class: "btn btn-primary" %>
      </div>
    <% end %>
</div>

<script>

  $('#calendar').fullCalendar({
   selectable: true,
   header: {
     left: 'prev',
     center: 'title',
   },
   events:

   "/live_house/lives/new" + ".json",//"lives/new.json"

   eventOverlap: false,
   validRange: function(nowDate){
     return {
     start: nowDate.clone().add(6, 'months'),
     end: nowDate.clone().add(24, 'months')
     };
   },

   color: 'yellow',
   textColor: 'black',

   select: function(startDate, endDate) {
     $('#new_live').modal('show');
     $(".input-start").val(moment(startDate).format("YYYY-MM-DD"));
     $(".input-end").val(moment(endDate).format("YYYY-MM-DD"));
   }
  });
</script>