config/routes.rb
Rails.application.routes.draw do

  devise_for :live_houses, controllers: {
    sessions: "devise/live_houses/sessions",
    registrations: "devise/live_houses/registrations"
  }

  devise_for :users, skip: [:registrations, :sessions ]

  devise_scope :user do
    get 'signin' => 'devise/users/sessions#new', as: :new_user_session
    post 'signin' => 'devise/users/sessions#create', as: :user_session
    delete 'sign_out' => 'devise/users/sessions#destroy', as: :destroy_user_session
    get 'signup' => 'devise/users/registrations#new', as: :new_user_registration
    post 'signup' => 'devise/users/registrations#create', as: :user_registration
    post 'guest_sign_in' => 'devise/users/sessions#guest_sign_in', as: :user_guest_sign
  end

  devise_for :admins, controllers: {
    sessions: "devise/admins/sessions",
    registrations: "devise/admins/registrations"
  }

  namespace :live_house do
    get 'calendar' => 'lives#calendar'
    resources :mypages, only:[:new, :show, :edit]
    resources :schedules, only:[:index]
    resources :lives, only:[:new, :create, :show]
    resources :user, only:[:show]
  end

  scope module: :public do
    root to: 'homes#top'
    get 'home_lives' => 'homes#lives'
    resources :live_houses, only: [:index, :show]
    resources :favorites, only: [:create, :destroy]
    resources :live_organizations, only: [:create]
    resources :lives, only: [:new, :create, :show]
    get 'calendar' => 'lives#calendar'
    resources :notifications, only: :index
    resources :relationships, only: [:create, :destroy]
    resources :bands, only:[:index, :edit, :update]
    resources :articles, only:[:show, :create, :destroy] do
      resource :favorites, only: [:create, :destroy]
      resources :comments, only: [:create, :destroy]
    end

    get 'users/:id/edit' => 'users#edit' ,as: 'edit_mypage'
    get 'users/:id' => 'users#show', as: 'mypage'
    patch 'users/mypage/update' => 'users#update'
    resources :bands do
      member do
        get :following, :followers
      end
    end
  end

  namespace :admin do
    root to: 'homes#top'
    resources :user_bands, only:[:index, :show, :update]
    resources :users, only:[:index, :show]
    resources :live_houses, only:[:edit, :show, :index, :update]
    resources :lives, only:[:index, :edit, :update]
  end

  if Rails.env.development?
    mount LetterOpenerWeb::Engine, at: '/letter_opener'
  end
end

app/models/band.rb
class Band < ApplicationRecord
  belongs_to :user
  has_many :articles, dependent: :destroy
  has_many :comments
  has_many :members

  has_many :active_relationships, class_name:  "Relationship",
                                  foreign_key: "follower_id",
                                  dependent:   :destroy
  has_many :passive_relationships, class_name: "Relationship",
                                   foreign_key: "followed_id",
                                   dependent:  :destroy
  has_many :following, through: :active_relationships, source: :followed
  has_many :followers, through: :passive_relationships, source: :follower

  # iine機能
  has_many :favorites, dependent: :destroy

  # live開催
  has_many :live_organizations
  has_many :lives, through: :live_organizations, source: :live

  # 通知機能
  has_many :active_notifications, class_name: 'Notification', foreign_key: 'visitor_id', dependent: :destroy
  has_many :passive_notifications, class_name: 'Notification', foreign_key: 'visited_id', dependent: :destroy

  # band情報とmember情報を同時にcreate
  accepts_nested_attributes_for :members, allow_destroy: true

  validates_associated :members

  # 自身では無い時follow
  def follow(other_band)
    self.following << other_band
  end

  # followの解除
  def unfollow(other_band)
    active_relationships.find_by(followed_id: other_band.id).destroy
  end

  # 既にfollowをしているか？
  def following?(other_band)
    following.include?(other_band)
  end

  # followに関する通知を作成
  def create_notification_follow!(current_band)
    temp = Notification.where(["visitor_id = ? and visited_id = ? and action = ? ", current_band.id, id, 'follow'])
    if temp.blank?
      notification = current_band.active_notifications.new(
        visited_id: id,
        action: 'follow'
      )
      notification.save if notification.valid?
    end
  end

  def member_name_role
    member_array = members.map { |member| member.name + "(#{member.role})" }
    member_array.join(" , ")
  end
end

app/models/user.rb
class User < ApplicationRecord
  attachment :profile_image
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_one :band

  accepts_nested_attributes_for :band
  validates :user_name, presence: true
  validates :last_name_kana, format:
    {
      with: /\A[\p{katakana}　ー－&&[^ -~｡-ﾟ]]+\z/,
      message: "全角カタカナのみで入力して下さい",
    }, if: :persisted?
  validates :first_name_kana, format:
    {
      with: /\A[\p{katakana}　ー－&&[^ -~｡-ﾟ]]+\z/,
      message: "全角カタカナのみで入力して下さい",
    }, if: :persisted?

  def current_user?(user)
    self == user
  end

  def name
    [first_name, last_name].join(' ')
  end

  def kana_name
    [first_name_kana, last_name_kana].join(' ')
  end

  def self.guest
    find_or_create_by!(email: 'guest@example.com') do |user|
      user.user_name = 'guest'
      user.password = SecureRandom.urlsafe_base64
      user.band = Band.find_or_create_by(band_name: 'guest')
    end
  end
end

app/controllers/admin/users_controller.rb
class Admin::UsersController < ApplicationController
  skip_before_action :authenticate_user!
  before_action :authenticate_admin!

  def index
    @users = User.all.includes(:band)
  end

  def show
    @user = User.find(params[:id])
    @band = @user.band
    @articles = Article.where(band_id: @band.id).page(params[:page]).reverse_order
    # live情報()
    @gather_bands = @band.lives
  end
end

app/helpers/admin/users_helper.rb
module Admin::UsersHelper
end

app/views/admin/users/index.html.erb
<div class="container">
  <div class="row">
    <h1>Users</h1>
    <table class="table table-dark table-sm">
      <thead>
        <tr>
          <th>User ID</th>
          <th>User name</th>
          <th>Band</th>
          <th>status</th>
          <th></th>
        </tr>
      </thead>
      <tbody>
        <% @users.each do |user| %>
        <tr>
          <td><%= user.id %></td>
          <td><%= user.user_name %></td>
          <td><%= user.band.band_name %></td>
          <td><%= user.is_active %></td>
          <td></td>
        </tr>
        <% end %>
      </tbody>
    </table>
  </div>
</div>

app/views/admin/users/show.html.erb
<div class="container">

  <div class="modal fade" id="user-modal"></div>

  <div class="row mb-4">
    <div class="col-sm-4 text-center">
      <div class="row mb-3">
        <div class="co-sm-4 offset-sm-4">
          <%= attachment_image_tag @user, :profile_image, size: "100x100", fallback: "no_image.png", size: "100x100", class:"rounded-circle" %>
        </div>
      </div>
      <div class="row">
        <div class="col-4 offset-2"><%= @band.followings.count.to_s%>フォロー中</div>
        <div class="col-4"><%= @band.follower_ids.count%>フォロワー</div>
      </div>
    </div>
  　<div class="col-sm-4">
  　   <table>
        <tbody>
          <tr>
            <td><%= User.human_attribute_name(:user_name)%></td>
            <td> : <%= @user.user_name%></td>
          </tr>
          <tr>
            <td><%= User.human_attribute_name(:email)%></td>
            <td> : <%= @user.email%></td>
          </tr>
          <tr>
            <td><%= Band.human_attribute_name(:band_name)%></td>
            <td> : <%= @band.band_name%></td>
          </tr>
        </tbody>
      </table>
    </div>
  </div>

  <div class="row">
    <div class="col-6">
      <div class="card-list">
          <% @articles.each do |article| %>
            <%= link_to article_path(article), class:"card-link" do%>
            <div class="card w-auto mx-auto mt-4 shadou-lg">
              <div class="card-body">
                <div class="row">
                  <div class="col-3">
                    <%= attachment_image_tag article.band.user, :profile_image, size: "60x60" , fallback: "no_image.png" ,
                      size: "60x60" , class:"mt-2 rounded-circle"%>
                  </div>
                  <div class="col-9">
                    <div class="row">
                      <%= article.band.band_name%>
                    </div>
                    <div class="row">
                      <%= article.content%>
                    </div>
                  </div>
                </div>
                <div class="row">
                  <div class="col-3">
                   ♥<%= article.favorites.count %> いいね
                  </div>
                  <div class="col-3">
                    <%= article.comments.count %>コメント
                  </div>
                </div>
              </div>
            </div>
            <% end %>
          <% end %>
          <%= paginate @articles %>
      </div>
    </div>

    <div class="col-6">

      <div class="row card border-primary mb-3 bg-transparent">
        <div class="card-header bg-transparent"><h3>New live</h3></div>
        <div class="card-body text-primary">
          <% @gather_bands.waiting_live.each do |waiting_live| %>
            <h5 class="card-title"><%= waiting_live.live_name %></h5>
            <%= waiting_live.start_at %>
          <% end %>
        </div>
      </div>

      <div class="row card border-primary mb-3 bg-transparent">
        <div class="card-header"><h3>Gathering Bands</h3></div>
        <div class="card-body text-primary">
          <% @gather_bands.gathering.each do |gathering| %>
            <div><%= gathering.start_time %>：<%= gathering.live_name %></div>
          <% end %>
        </div>
      </div>

      <div class="row card border-primary mb-3 bg-transparent">
        <div class="card-header"><h3>Live History</h3></div>
        <div class="card-body text-primary">
          <% @gather_bands.finish_live.each do |gathered| %>
            <h5 class="card-title"><%= gathered.live_name %></h5>
            <%= gathered.start_time %>
          <% end %>
        </div>
      </div>

      <div class="row card border-primary mb-3">
        <div class="card-header text-dark"><h3>User info</h3></div>
        <div class="card-body text-dark">
          <h5 class="card-title"><%= @user.user_name %></h5>

          <table>
            <tbody>
              <tr>
                <td>email</td>
                <td>：<%= @user.email%></td>
              </tr>
              <tr>
                <td>name</td>
                <td>：<%= @user.name%></td>
              </tr>
              <tr>
                <td>Kana name</td>
                <td>：<%= @user.kana_name%></td>
              </tr>
              <tr>
                <td>Band name</td>
                <td>：<%= @band.band_name%></td>
              </tr>
              <tr>
                <td>Postal code</td>
                <td>：<%= @band.band_name%></td>
              </tr>
              <tr>
                <td>Address</td>
                <td>：<%= @user.address%></td>
              </tr>
              <tr>
                <td>Telephone number</td>
                <td>：<%= @user.telephone_number%></td>
              </tr>
            </tbody>
          </table>
        </div>
      </div>
    </div>
  </div>

</div>