config/routes.rb
Rails.application.routes.draw do

  devise_for :live_houses, controllers: {
    sessions: "devise/live_houses/sessions",
    registrations: "devise/live_houses/registrations"
  }

  devise_for :users, skip: [:registrations, :sessions ]

  devise_scope :user do
    get 'signin' => 'devise/users/sessions#new', as: :new_user_session
    post 'signin' => 'devise/users/sessions#create', as: :user_session
    delete 'sign_out' => 'devise/users/sessions#destroy', as: :destroy_user_session
    get 'signup' => 'devise/users/registrations#new', as: :new_user_registration
    post 'signup' => 'devise/users/registrations#create', as: :user_registration
    post 'guest_sign_in' => 'devise/users/sessions#guest_sign_in', as: :user_guest_sign
  end

  devise_for :admins, controllers: {
    sessions: "devise/admins/sessions",
    registrations: "devise/admins/registrations"
  }

  namespace :live_house do
    get 'calendar' => 'lives#calendar'
    resources :mypages, only:[:new, :show, :edit]
    resources :schedules, only:[:index]
    resources :lives, only:[:new, :create, :show]
    resources :user, only:[:show]
  end

  scope module: :public do
    root to: 'homes#top'
    get 'home_lives' => 'homes#lives'
    resources :live_houses, only: [:index, :show]
    resources :favorites, only: [:create, :destroy]
    resources :live_organizations, only: [:create]
    resources :lives, only: [:new, :create, :show]
    get 'calendar' => 'lives#calendar'
    resources :notifications, only: :index
    resources :relationships, only: [:create, :destroy]
    resources :bands, only:[:index, :edit, :update]
    resources :articles, only:[:show, :create, :destroy] do
      resource :favorites, only: [:create, :destroy]
      resources :comments, only: [:create, :destroy]
    end

    get 'users/:id/edit' => 'users#edit' ,as: 'edit_mypage'
    get 'users/:id' => 'users#show', as: 'mypage'
    patch 'users/mypage/update' => 'users#update'
    resources :bands do
      member do
        get :following, :followers
      end
    end
  end

  namespace :admin do
    root to: 'homes#top'
    resources :user_bands, only:[:index, :show, :update]
    resources :users, only:[:index, :show]
    resources :live_houses, only:[:edit, :show, :index, :update]
    resources :lives, only:[:index, :edit, :update]
  end

  if Rails.env.development?
    mount LetterOpenerWeb::Engine, at: '/letter_opener'
  end
end

app/views/layouts/_error_messages.html.erb
<% if model.errors.any? %>
  <div class="alert alert-danger">
    <ul>
      <% model.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/layouts/_validation_errors.html.erb
<% if instance.errors.full_messages.present? %>
  <div class="validates js-message-errors">
    <ul>
      <% instance.errors.full_messages.each do |msg| %>
        <li style="color: #bb4a4a;"><%= msg %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <meta name="viewport" content="width=device-width">
    <title>GatherBands</title>
    <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application' %>
  </head>

  <body>
    <header>
      <h1>
        <%= link_to GatherBands,root_path %>
      </h1>
      <div class="pc-menu">
        <nav>
          <ul>
            <% if user_signed_in? %>
              <li><%= link_to "New",notifications_path %></li>
              <li class="dropdown-child live-info">
                <span>live info</span>
                <ul class="dropdown_menu">
                  <li><%= "Live House" %></li>
                  <li><%= "Lives" %></li>
                </ul>
              </li>              
              <li><%= link_to "Mypage",mypage_path(current_user) %></li>
              <li><%= link_to "Bands",bands_path %></li>
              <li><%= link_to "Log out",destroy_user_session_path, method: :delete %>
            <% elsif admin_signed_in? %>
              <li><%= link_to "Users",admin_users_path %></li>
              <li class="dropdown-child live-info">live info
                <ul class="dropdown_menu">
                  <li><%= link_to "Live House",admin_live_houses_path, class:"nav-link"%></li>
                  <li><%= link_to "Lives",admin_lives_path, class:"nav-link"%></li>
                </ul>
              </li>
              <li><%= link_to "Log out",destroy_user_session_path, method: :delete %></li>
            <% elsif live_house_signed_in? %>
              <li><%= link_to "Live Schedule",live_house_schedules_path %></li>
              <li><%= link_to "My house",live_house_mypage_path(current_live_house) %></li>
              <li><%= link_to "Log out",destroy_live_house_session_path, method: :delete %></li>
            <% else %>
              <li class="modalopen"><span>Log in</span></li>
              <li><%= link_to "Sign up",new_user_registration_path %></li>
            <% end %>
          </ul>
        </nav>
      </div>
      
      <div class="sp-menu">
        <span class="material-icons" id="open">menu</span>
      </div>
      
    </header>
    
    <div class="overlay">
      <span class="material-icons" id="close">close</span>
      <nav>
        <ul>
          <% if user_signed_in? %>
            <li><%= link_to "New",notifications_path %></li>
            <li><%= link_to "Lives",home_lives_path %></li>
            <li><%= link_to "Live Houses",live_houses_path %><li>
            <li><%= link_to "Mypage",mypage_path(current_user) %></li>
            <li><%= link_to "Bands",bands_path %></li>
            <li><%= link_to "Log out",destroy_user_session_path, method: :delete %>
          <% elsif admin_signed_in? %>
            <li><%= link_to "Users",admin_users_path %></li>
            <li><%= link_to "Live House",admin_live_houses_path, class:"nav-link"%></li>
            <li><%= link_to "Lives",admin_lives_path, class:"nav-link"%></li>
            <li><%= link_to "Log out",destroy_user_session_path, method: :delete %></li>
          <% elsif live_house_signed_in? %>
            <li><%= link_to "Live Schedule",live_house_schedules_path %></li>
            <li><%= link_to "My house",live_house_mypage_path(current_live_house) %></li>
            <li><%= link_to "Log out",destroy_live_house_session_path, method: :delete %></li>
          <% else %>
            <li class="modalopen">Log in</li>
            <li><%= link_to "Sign up",new_user_registration_path %></li>
          <% end %>
        </ul>
      </nav>
    </div>
    
    <main>
      <%= yield %>
    </main>

    <div class="container">
      <footer>
        <small>
          Gather Bands by <a>Zhong Zhi</a>
        </small>
        <nav>
          <ul>
            <li><%= link_to "Live House",new_live_house_session_path, class:"nav-link" %></li>
          </ul>
        </nav>
      </footer>
    </div>
    
    
    <%= javascript_include_tag 'humbarger-menu.js' %>
    <%= javascript_include_tag 'login.js' %>
    <%= javascript_include_tag 'application.js' %>
  </body>
</html>